### ISSUE TITLE
The test matrix (Pass/Fail/Na) isn't shown for some modules

### ISSUE THREAD

**Issue by Astara** [CPAN-API/metacpan-web#1046]
Example.

When I look at "https://metacpan.org/release/LAWALSH/P-1.0.20", there is nothing after the "Test results " section except a smallish iconic-looking matrix.

On other modules, say, Test::Simple, I see:
Test results (1153 / 5 / 0)
-- a list of results..

Why are test results not shown on the first example but are shown on the 2nd example?

**Comment by ranguard** [comment]
https://github.com/CPAN-API/metacpan-web/blob/master/root/inc/release-info.html#L42 is the logic for what is displayed, I'm not sure what sets `release.tests.size`

**Comment by rwstauner** [comment]
`.size` is a virtual method provided by the template... it's the "size" of the array.

`release.tests` are indexed from the cpan-testers database we download.

The problem is the way the two systems link:
```
*sqlite> select * from release where dist = 'P' and version LIKE '%1.0.20%';
dist  version        pass  fail  na    unknown
----  -------------  ----  ----  ----  -------------
P     1.0.20         207   15    9     0
```
and
```
💥  curl 'api.metacpan.org/release/LAWALSH/P-1.0.20?fields=name,distribution,version'
{
   "version" : "v1.0.20",
   "distribution" : "P",
   "name" : "P-1.0.20"
}
```

The script that indexes test results combines "$dist-$version" from each source, and unfortunately that "v" is present in one and not the other, so the link is not found.
So essentially we need the indexer to work a little harder to link the two.
In this case using the release name would be a better link, however I'm sure there are dists out there that leave the "v" in the archive name.  It might help to learn how cpan testers gets the version that it uses in its database.

**Comment by rwstauner** [comment]
This has been fixed.  Thanks for reporting!
