### ISSUE TITLE
Issue counts are incorrect for Google Code queues

### ISSUE THREAD

**Issue by karenetheridge** [CPAN-API/metacpan-web#1450]
e.g.: https://metacpan.org/release/B-C

The mouseover on 'issues' says "1" (presumably because there is one ticket at https://rt.cpan.org/Dist/Display.html?Queue=B-C), but the issues link actually goes to https://code.google.com/p/perl-compiler/issues/list where there are many issues.

If the tracker is something that is not understood, the count should just say "unknown".

(Perhaps a separate count could be used for RT, that didn't make it seem that the RT count was the official queue's count.)

**Comment by ranguard** [comment]
Closing because:

1) really needs to be cleaned up in the API so that the issue could source is clearer, so if anything an API issue
2) code.google.com is going into read-only August 24, 2015 and shutdown January 25, 2016  [see here](http://google-opensource.blogspot.co.uk/2015/03/farewell-to-google-code.html)

**Comment by ranguard** [comment]
Ok, that turned out to be crap, it is sort of in the API

**Comment by ranguard** [comment]
Bah I seem to have tricked my self into a pull request:
https://github.com/CPAN-API/metacpan-web/pull/1475

**Comment by karenetheridge** [comment]
ranguard++
