### ISSUE TITLE
Add support for Changes.pod?

### ISSUE THREAD

**Issue by zhouzhen1** [CPAN-API/metacpan-web#1471]
Some distributions have a "Changes.pod" file instead of a plain "Changes", for example
https://metacpan.org/release/Set-Object

But the "Changes" link does not support Changes.pod..

**Comment by oalders** [comment]
This is related to (but not affected by) #1463 Thoughts on this, @karenetheridge?

**Comment by rwstauner** [comment]
I've heard some arguments for "installing" the changelog... it can be useful to look for something if you notice an issue.  For example, DBI has [DBI::Changes.pod](https://metacpan.org/pod/distribution/DBI/Changes).

**Comment by rwstauner** [comment]
The difference (if there is any) from #1463 is that those files are often generated (from other copies) but Changes might still be kept up manually.

**Comment by karenetheridge** [comment]
I don't think there's a right answer here - either way bad things *could* happen -- a Changes.pod could be put into the distribution because the author likes that markup format, and not intend the file to be installed... or he could very intentionally want it installed (e.g. DBI) -- but in the latter case, there is a way of indicating that this is intentional - by putting the file not in the repository root but in lib/DBI/Changes.pod.

**Comment by ranguard** [comment]
Closing as no action taken
