### ISSUE TITLE
Disallow robots on old POD pages

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/metacpan-web#1545]
Wouldn't it be better to disallow robots for any pages under https://metacpan.org/pod/release/ that are the pods for old versions modules?
Are there any pages that appear only there?

**Comment by ranguard** [comment]
@rwstauner ?

**Comment by rwstauner** [comment]
This might be true if we assumed that dists never removed pod files (or, for any that were, that this means they are no longer valid).

You could perhaps consider this if your goal was to aggressively hide content from bots, however there may be legitimate use cases that we'd then be disallowing.

If a dist has a "work around" pod for an old version, then eventually removes that pod...
If someone is using an old version (or updates and can't remember what the old one said) and goes searching, they wouldn't find the info.

For the majority of cases (where dists keep roughly the same pod files for their lifetime) this would probably be ok, but there are plenty of cases where we'd be explicitly expiring content that might still be worth finding for some.

We do have canonical link references so that bots that understand those should recognize pages that have newer versions.

FWIW sco does not do this.
I don't really think it's the right approach either, but I'm willing to hear additional arguments.

**Comment by ranguard** [comment]
Thanks @rwstauner .. so after a bit of investigation on canonical... we SHOULD allow this in robots.txt...

https://support.google.com/webmasters/answer/139066?hl=en

"Consolidating link signals for the duplicate or similar content. It helps search engines to be able to consolidate the information they have for the individual URLs (such as links to them) on a single, preferred URL."

So links to any version, eg. https://metacpan.org/pod/release/SHAY/perl-5.20.2/pod/perl.pod
will increase the page rank for https://metacpan.org/pod/distribution/perl/pod/perl.pod

This is a big enough reason for us to keep it IMHO. Setting a long cache control header so bots/users don't re-request it so often if it is under /pod/release might be the way to go, I'm trying to review all cacheing at the moment, so closing this ticket. @szabgab thanks for the prompt though!
