### ISSUE TITLE
Error rendering POD for ... - Requested resource is too large to be processed

### ISSUE THREAD

**Issue by book** [CPAN-API/metacpan-web#1561]
I see the above error message for <https://metacpan.org/pod/Image::ExifTool::TagNames#PNG-TextualData-Tags>. It seems to be [a known issue for a long time](http://irclog.perlgeek.de/metacpan/2012-09-07#i_5969828).

[Maybe the size limit could be increased?](https://github.com/CPAN-API/cpan-api/blob/master/lib/MetaCPAN/Server/Controller/Pod.pm#L20)

**Comment by oalders** [comment]
Can anyone think of a reason not to merge this?

**Comment by oalders** [comment]
Code in question is being deployed right now. Thanks for this.

**Comment by oalders** [comment]
It works now but will require a hard refresh.

**Comment by thruston** [comment]
I'm still seeing this message with my module
https://metacpan.org/pod/Geo::Coordinates::OSGB
In my case there are only 820 lines of code + pod, but there are 2.6M bytes of data lines following the __DATA__ marker.   The data is a vital part of the module, and keeping it all under __DATA__ is much much faster than any external shared file solution that I've found so far, so I'm reluctant to try any other solution.  

Can we find a more sophisticated way of working out the size of the file?  Perhaps extract the text with Pod::Text and measure that?  

Otherwise, can you consider raising the size limit again?  2**22 would be enough for me.
