### ISSUE TITLE
DBD::mysql::INSTALL doesn't get indexed as pod or Documentation

### ISSUE THREAD

**Issue by Grinnz** [CPAN-API/metacpan-web#1576]
The documentation file DBD::mysql::INSTALL doesn't show up under Documentation for DBD::mysql, and https://metacpan.org/pod/DBD::mysql::INSTALL doesn't work. But it is just a .pod file in lib/, the same as Mojolicious::Guides, but those show up in both instances.

https://metacpan.org/pod/release/CAPTTOFU/DBD-mysql-4.032/lib/DBD/mysql/INSTALL.pod
https://metacpan.org/pod/Mojolicious::Guides

**Comment by rwstauner** [comment]
I'd guess the file is being treated as an "other" file because of it's base name:
https://github.com/CPAN-API/cpan-api/blob/master/lib/MetaCPAN/Document/File.pm#L717

However it probably doesn't show up in the "other files" section on the release page because it isn't in the root of the archive.

So there's an inconsistency there that we should remedy.

**Comment by nwellnhof** [comment]
Probably the same issue as #1482. Can we please revert the blacklisting of `INSTALL.pod` and `README.pod` introduced by commit 84bfc77?

**Comment by nwellnhof** [comment]
Original issue that prompted the blacklisting: #1463

**Comment by Grinnz** [comment]
Reverting that commit would not be ideal. That is intended to deal with files in the root of the repository, whereas this .pod file is not in the root, so it should not be getting any special treatment.

**Comment by mbeijen** [comment]
Hi there, I'm a co-maintainer of DBD::mysql; this issue is also reported as https://rt.cpan.org/Public/Bug/Display.html?id=106301

So what would be the best solution here? I was actually considering converting `INSTALL.pod` to `INSTALL.md`  but I'm afraid it will not work on search.cpan.org.  Also I kind of liked to have all documentation in POD.

I could probably convert to `DBD::mysql::INSTALL.pm` but that's not nice either because it'll actually install the installation documentation in `@INC`.

**Comment by Grinnz** [comment]
It already is installed in `@INC` in the current state so I would not see that as a problem -- that is how perldoc will find it anyway.

**Comment by mbeijen** [comment]
Maybe that will be the best solution then.

Op maandag 19 oktober 2015 heeft Dan Book <notifications@github.com> het
volgende geschreven:

**Comment by haarg** [comment]
I've made a PR meant to address this direct issue, because from what I know, we never meant to exclude files in subdirectories like DBD::mysql::INSTALL is doing.

Arguments over our handling of INSTALL/README files in the root of a dist can be handled in #1482.

**Comment by Grinnz** [comment]
Thanks haarg!
