### ISSUE TITLE
broken links to documentation

### ISSUE THREAD

**Issue by dk** [CPAN-API/metacpan-web#1660]
Hello,

There are links in my module that result in a 404 error, even though the same module on search.cpan.org is fine. Please take a look f.ex. at link to https://metacpan.org/pod/Prima::Grids that is found on https://metacpan.org/pod/Prima::tutorial page, and that is broken. The http://search.cpan.org/~karasik/Prima-1.46/pod/Prima/tutorial.pod, that resolves the module fine.

Sincerely,
Dmitry

**Comment by dk** [comment]
(also, "perldoc Prima::Grids" works well too)

**Comment by oalders** [comment]
Hi Dmitry,

Thanks for this.  Prima::Grids is not in `02packages.details.txt`, so that link won't work.  Also, it's a pod-only inner package without a package declaration.

The easy way to fix this would be to create a file in, eg `lib/Prima/Grids.pm`  Make sure it also contains a `package Prima::Grids` declaration.  If you upload this, then PAUSE should give you permissions on that package and add it to 02packages.  MetaCPAN will then also know where to look for it.  :)

Best,

Olaf

**Comment by dk** [comment]
Hi Olaf,

That seems to be working

Thank you!
Dmitry
